fixtures:
  symlinks:
    cassandra: "#{source_dir}"
  repositories:
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt"
      ref: "2.4.0"
    firewall: "git://github.com/puppetlabs/puppetlabs-firewall"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
