---
language: ruby
bundler_args: --without development
script:
  - "bundle exec rake lint"
  - "bundle exec rake syntax"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
notifications:
  email: false
sudo: false
rvm:
  - "2.2.0"
  - "2.1.0"
  - "2.0.0"
  - "1.9.3"
env:
  - BEAKER_set="centos-65-x64"
  - BEAKER_set="centos-7-x64"
  - BEAKER_set="ubuntu-server-1204-x64"
  - BEAKER_set="ubuntu-server-1404-x64"
