---
language: ruby
bundler_args: --without development
script:
  - "bundle exec rake lint"
  - "bundle exec rake syntax"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
notifications:
  email: false
sudo: false
rvm:
  - "2.0.0"
